name: Welcome New Contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  greet-new-contributor:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.type == 'User'

    steps:
      - name: Check if this is the user's first PR
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Welcome to the project! Thank you for your first pull request.  
            We appreciate your contribution. If you have any questions, feel free to ask. 🚀
